package com.vanamod.mod;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = VanaMod.MODID, version = VanaMod.VERSION, name = VanaMod.NAME)
public class VanaMod {

    public static final String MODID = "vanamod";
    public static final String NAME = "VanaMod";
    public static final String VERSION = "0.1";

    @Mod.Instance(MODID)
    public static VanaMod instance;

    // Tab créatif custom
    public static CreativeTabs vanaTab = new VanaModTab("vanamod");

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        System.out.println("[VanaMod] PreInitialization");
        // Enregistrer les items et armures
        ModItems.init();
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {
        System.out.println("[VanaMod] Initialization");
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        System.out.println("[VanaMod] PostInitialization");
    }
}